### ISSUE TITLE
Please add https://github.com/Jamling/jarsigner/ URL on https://marketplace.eclipse.org/content/jar-signer

### ISSUE THREAD

**Issue by paulvi** [Jamling/jarsigner#1]
Please add https://github.com/Jamling/jarsigner/ URL on https://marketplace.eclipse.org/content/jar-signer

e.g. http://www.ieclipse.cn/p/ as main URL and https://github.com/Jamling/jarsigner/  as support URL

**Comment by Jamling** [comment]
Solution URL and support URL changed to https://github.com/Jamling/jarsigner
